# Strings for Private\Checks.ps1.
@{
    'Checks.WorkDirIsRoot'       = 'it is the root of a drive'
    'Checks.WorkDirContainsPath' = 'it contains {0}, which would be deleted'
    'Checks.WorkDirIsFile'       = 'it is a file, not a folder'
    'Checks.WorkDirNotEmpty'     = 'the folder is not empty and was not created by this script'
    'Checks.WorkDirMarker'       = 'LunqDebloater working folder. It is deleted after the build.'
    'Checks.LeftoverMount'       = 'Found an image still mounted at {0} from an earlier run, unmounting it without saving.'
    'Checks.OutputIsSource'      = 'it is the source ISO, it would be overwritten'
    'Checks.OutputIsFolder'      = 'it is a folder, but a path to an .iso file is needed'
    'Checks.OutputNoFolder'      = 'the folder {0} does not exist, create it'
    'Checks.OutputNotWritable'   = 'files cannot be written to the folder {0}'
    'Checks.HostOlder'           = 'Windows on this computer (build {0}{1}) is older than the image ({2}). The DISM of this system may fail on some steps, most often when adding updates.'
    'Checks.WorkDirProblem'      = 'Working folder {0}: {1}'
    'Checks.WorkDirProblemHint'  = 'The script deletes everything in the working folder. Use -WorkDir to choose a new or empty folder, for example D:\LunqWork.'
    'Checks.OutputProblem'       = 'Final ISO {0}: {1}'
    'Checks.OutputProblemHint'   = 'Choose another path with -OutputIso.'
    'Checks.Adk'                 = 'Windows ADK: {0}'
    'Checks.AdkMissing'          = 'oscdimg.exe from the Windows ADK was not found'
    'Checks.AdkMissingHint'      = 'Install the ADK (the Deployment Tools component is enough): https://learn.microsoft.com/windows-hardware/get-started/adk-install'
    'Checks.WorkDirNetwork'      = 'The working folder {0} is on a network drive'
    'Checks.WorkDirNetworkHint'  = 'DISM can mount an image only on a local NTFS drive. Choose another folder with -WorkDir.'
    'Checks.OutputNetwork'       = 'The final ISO will be saved to a network folder, free space there is not checked.'
    'Checks.WorkDirNotNtfs'      = 'Drive {0} for the working folder is not NTFS ({1})'
    'Checks.WorkDirNotNtfsHint'  = 'DISM can mount an image only on NTFS. Choose another folder with -WorkDir.'
    'Checks.WorkSpaceOk'         = 'Space on {0} for the working folder: {1} free, about {2} needed'
    'Checks.WorkSpaceLow'        = 'Low space on {0}: {1} free, about {2} needed'
    'Checks.WorkSpaceLowHint'    = 'Free up space or use -WorkDir to choose a folder on another drive.'
    'Checks.OutputSpaceOk'       = 'Space on {0} for the final ISO: {1} free'
    'Checks.OutputSpaceLow'      = 'Low space on {0} for the final ISO: {1} free, about {2} needed'
    'Checks.OwnMount'            = 'An image from an interrupted run is still mounted, it will be unmounted without saving before the build'
    'Checks.ForeignMount'        = 'DISM images are already mounted on this system: {0}'
    'Checks.ForeignMountHint'    = 'If they are left over from an old run in another folder, run: dism /Cleanup-Wim'
}
