# Strings for Private\Iso.ps1.
@{
    'Iso.NoDriveLetter'         = 'Could not get the drive letter of the mounted ISO.'
    'Iso.NotWindowsIso'         = 'The ISO has no sources\install.wim or install.esd. It does not look like a Windows installation image.'
    'Iso.ArchMismatch'          = 'The image architecture is {0}, but the profile is made for {1}.'
    'Iso.BuildMismatch'         = 'The image build is {0}, but the profile is made for build {1}. You need an ISO of exactly this Windows version.'
    'Iso.RevisionOldWithUpdate' = 'The image build {0} is older than {1}, but the cumulative update from the updates folder will bring it up to date.'
    'Iso.RevisionTooOld'        = 'The image build {0} is older than the profile needs: {1} or newer.'
    'Iso.Copying'               = 'ISO mounted as {0}, copying files...'
    'Iso.RobocopyFailed'        = 'robocopy exited with code {0}'
    'Iso.NoInstallImage'        = 'No install.wim or install.esd found in the sources folder.'
    'Iso.HintProWorkstations'   = 'Pro for powerful workstations: ReFS, more processors and memory'
    'Iso.HintProEducation'      = 'Pro for schools and universities'
    'Iso.HintEducation'         = 'for schools and universities, close to Enterprise in features'
    'Iso.HintEnterprise'        = 'for organizations: everything in Pro plus business features, needs a volume license'
    'Iso.HintSingleLanguage'    = 'Home with a single display language, the language cannot be changed'
    'Iso.HintPro'               = 'BitLocker, Group Policy, Hyper-V, Remote Desktop; fits most people'
    'Iso.HintHome'              = 'for a home PC, without BitLocker, Group Policy and Hyper-V'
    'Iso.HintN'                 = '{0}. N edition: without media features'
    'Iso.AvailableEditions'     = 'Available editions:'
    'Iso.NoEditionIndex'        = 'The image has no edition number {0}. Pick a number from the list above.'
    'Iso.EditionNotFound'       = 'Edition ''{0}'' not found. Give a name from the list above in quotes, or a number with -Index.'
    'Iso.SingleEdition'         = 'The image has one edition: {0}'
    'Iso.ChooseEdition'         = 'Which Windows edition should be prepared? Only this one will stay in the final ISO.'
    'Iso.ChooseEditionHint'     = 'If unsure, pick the one you have a product key for (usually Home or Pro).'
    'Iso.EditionPrompt'         = 'Enter the edition number'
    'Iso.NoSuchNumber'          = 'That number is not in the list, try again.'
    'Iso.DialogTitle'           = 'Select a Windows 11 ISO image'
    'Iso.DialogFilter'          = 'Disc image (*.iso)|*.iso'
    'Iso.SelectCancelled'       = 'ISO selection cancelled.'
    'Iso.PathPrompt'            = 'Path to the ISO (you can drag the file into this window)'
    'Iso.FileNotIso'            = 'File not found or not an ISO: {0}'
}
