# Strings for Private\Profile.ps1.
@{
    'Profile.NotFound'             = 'Profile not found: {0}'
    'Profile.CategoryNoId'         = 'In profile {0}, one of the categories has no Id.'
    'Profile.CategoryIdRepeated'   = 'In profile {0}, the category Id ''{1}'' is used more than once.'
    'Profile.DefaultCategoryName'  = 'Profile'
    'Profile.UnknownHive'          = 'Unknown hive ''{0}'' in category ''{1}''. Allowed: {2}'
    'Profile.RegistryNoPath'       = 'A registry entry for hive {0} in category ''{1}'' has no Path.'
    'Profile.RegistryEntryProblem' = 'Registry entry {0}\{1} in category ''{2}'': {3}'
    'Profile.CountAppx'            = 'apps: {0}'
    'Profile.CountCapabilities'    = 'capabilities: {0}'
    'Profile.CountFeatures'        = 'features: {0}'
    'Profile.CountPackages'        = 'packages: {0}'
    'Profile.CountRegistry'        = 'registry: {0}'
    'Profile.CategoryNotFound'     = 'The profile has no category ''{0}''. Available Ids: {1}'
    'Profile.CategoriesIntro'      = 'Profile categories. [x] will be applied, [ ] skipped.'
    'Profile.CategoriesPrompt'     = 'Category numbers to turn them on or off (separated by spaces), or Enter to continue'
    'Profile.NoSuchCategoryNumber' = 'Number {0} is not in the list.'
    'Profile.NoProfiles'           = 'The folder {0} has no profiles (*.json).'
    'Profile.Single'               = 'Profile: {0}'
    'Profile.ChooseIntro'          = 'The profile decides what is removed and changed in the image:'
    'Profile.Prompt'               = 'Enter the profile number'
    'Profile.NoSuchNumber'         = 'That number is not in the list, try again.'
}
