# Strings for Private\Registry.ps1.
@{
    'Registry.HiveLoadFailed'       = 'Could not load hive {0}'
    'Registry.HiveUnloadFailed'     = 'Could not unload {0}. Unload it manually: reg unload {0}'
    'Registry.NeedNumber'           = 'a number is required'
    'Registry.NotNumber'            = '''{0}'' is not a number'
    'Registry.DwordOverflow'        = '{0} does not fit in REG_DWORD'
    'Registry.NotHex'               = '''{0}'' is not a hex string (pairs of digits 0-9, A-F)'
    'Registry.NoType'               = 'Type is missing. Allowed: REG_SZ, REG_EXPAND_SZ, REG_MULTI_SZ, REG_DWORD, REG_QWORD, REG_BINARY'
    'Registry.UnknownType'          = 'unknown type ''{0}''. Allowed: REG_SZ, REG_EXPAND_SZ, REG_MULTI_SZ, REG_DWORD, REG_QWORD, REG_BINARY'
    'Registry.UnknownRoot'          = 'Unknown registry root: {0}'
    'Registry.UnknownActionAllowed' = 'unknown action ''{0}''. Allowed: {1}'
    'Registry.UnknownAction'        = 'unknown action ''{0}'''
    'Registry.DefaultValueName'     = '(Default)'
    'Registry.ApplyFailed'          = 'Could not apply {0}\{1} ({2}): {3}'
    'Registry.StampNone'            = 'no'
    'Registry.StampPartial'         = 'The build stamp was only partly written: {0}'
    'Registry.StampWritten'         = 'The build stamp was written to the image registry: HKLM\SOFTWARE\LunqDebloater.'
    'Registry.StampFailed'          = 'Could not write the build stamp: {0}'
    'Registry.Title'                = 'Registry'
    'Registry.ListEmpty'            = 'The registry tweak list in the profile is empty.'
    'Registry.Summary'              = 'Registry: applied {0}, skipped (already gone) {1}, errors {2}.'
}
