# Strings for Private\Servicing.ps1.
@{
    'Servicing.UpdatesTitle'    = 'Updates'
    'Servicing.DriversTitle'    = 'Drivers'
    'Servicing.UpdatesIn'       = 'Updates in {0}'
    'Servicing.DriversIn'       = 'Drivers in {0}'
    'Servicing.WhereSetup'      = 'Windows Setup'
    'Servicing.Installing'      = '[{0}/{1}] Installing {2} ({3})...'
    'Servicing.UpdateFailed'    = 'Could not install {0}: {1}'
    'Servicing.DriverFailed'    = 'Could not add {0}: {1}'
    'Servicing.Cleanup'         = 'Removing old file versions left after the updates...'
    'Servicing.NoWinre'         = 'The image has no Windows\System32\Recovery\Winre.wim, skipping the recovery environment.'
    'Servicing.NoBootWim'       = 'The ISO has no sources\boot.wim, so Windows Setup cannot be updated.'
    'Servicing.Recompressing'   = 'Recompressing {0}...'
    'Servicing.SizeChange'      = '{0}: was {1}, now {2}'
    'Servicing.SafeOSIn'        = 'Safe OS Dynamic Update in {0}'
    'Servicing.SetupDUTitle'    = 'Setup Dynamic Update'
    'Servicing.Expanding'       = '[{0}/{1}] Expanding {2} ({3}) into sources...'
    'Servicing.ExpandFailed'    = 'Could not expand {0}: expand.exe returned code {1}'
    'Servicing.SetupFilesTitle' = 'Setup files'
    'Servicing.SetupFilesDone'  = '{0} copied from boot.wim to sources'
    'Servicing.SetupFileFailed' = 'Could not copy {0} from boot.wim to sources: {1}'
}
