# Строки Private\Checks.ps1.
@{
    'Checks.WorkDirIsRoot'       = 'это корень диска'
    'Checks.WorkDirContainsPath' = 'внутри неё лежит {0}, он был бы удалён'
    'Checks.WorkDirIsFile'       = 'это файл, а не папка'
    'Checks.WorkDirNotEmpty'     = 'папка не пустая и создана не этим скриптом'
    'Checks.WorkDirMarker'       = 'Рабочая папка LunqDebloater. Удаляется после сборки.'
    'Checks.LeftoverMount'       = 'Найден оставшийся смонтированный образ в {0}, отключаю без сохранения.'
    'Checks.OutputIsSource'      = 'это исходный ISO, он был бы перезаписан'
    'Checks.OutputIsFolder'      = 'это папка, а нужен путь к файлу .iso'
    'Checks.OutputNoFolder'      = 'папки {0} нет, создайте её'
    'Checks.OutputNotWritable'   = 'в папку {0} нельзя записать файл'
    'Checks.HostOlder'           = 'Windows на этом компьютере (сборка {0}{1}) старше образа ({2}). DISM этой системы может не справиться с частью шагов, чаще всего со встраиванием обновлений.'
    'Checks.WorkDirProblem'      = 'Рабочая папка {0}: {1}'
    'Checks.WorkDirProblemHint'  = 'Скрипт полностью очищает рабочую папку. Укажите через -WorkDir новую или пустую папку, например D:\LunqWork.'
    'Checks.OutputProblem'       = 'Итоговый ISO {0}: {1}'
    'Checks.OutputProblemHint'   = 'Укажите другой путь через -OutputIso.'
    'Checks.Adk'                 = 'Windows ADK: {0}'
    'Checks.AdkMissing'          = 'Не найден oscdimg.exe из Windows ADK'
    'Checks.AdkMissingHint'      = 'Установите ADK (достаточно компонента Deployment Tools): https://learn.microsoft.com/windows-hardware/get-started/adk-install'
    'Checks.WorkDirNetwork'      = 'Рабочая папка {0} на сетевом диске'
    'Checks.WorkDirNetworkHint'  = 'DISM монтирует образ только на локальном NTFS-диске. Укажите другую папку через -WorkDir.'
    'Checks.OutputNetwork'       = 'Итоговый ISO будет сохранён в сетевую папку, свободное место там не проверяется.'
    'Checks.WorkDirNotNtfs'      = 'Диск {0} для рабочей папки не NTFS ({1})'
    'Checks.WorkDirNotNtfsHint'  = 'DISM монтирует образ только на NTFS. Укажите другую папку через -WorkDir.'
    'Checks.WorkSpaceOk'         = 'Место на {0} для рабочей папки: свободно {1}, нужно около {2}'
    'Checks.WorkSpaceLow'        = 'Мало места на {0}: свободно {1}, нужно около {2}'
    'Checks.WorkSpaceLowHint'    = 'Освободите место или укажите папку на другом диске через -WorkDir.'
    'Checks.OutputSpaceOk'       = 'Место на {0} для итогового ISO: свободно {1}'
    'Checks.OutputSpaceLow'      = 'Мало места на {0} для итогового ISO: свободно {1}, нужно около {2}'
    'Checks.OwnMount'            = 'Остался образ от прерванного запуска, он будет отключён без сохранения перед сборкой'
    'Checks.ForeignMount'        = 'В системе уже есть смонтированные образы DISM: {0}'
    'Checks.ForeignMountHint'    = 'Если это остатки старого запуска в другой папке, выполните: dism /Cleanup-Wim'
}
