# Строки Private\Iso.ps1.
@{
    'Iso.NoDriveLetter'         = 'Не удалось получить букву диска подключённого ISO.'
    'Iso.NotWindowsIso'         = 'В ISO нет sources\install.wim или install.esd. Похоже, это не установочный образ Windows.'
    'Iso.ArchMismatch'          = 'Архитектура образа {0}, а профиль рассчитан на {1}.'
    'Iso.BuildMismatch'         = 'Сборка образа {0}, а профиль рассчитан на сборку {1}. Нужен ISO именно этой версии Windows.'
    'Iso.RevisionOldWithUpdate' = 'Сборка образа {0} старше {1}, но накопительное обновление из папки обновлений её поднимет.'
    'Iso.RevisionTooOld'        = 'Сборка образа {0} старше, чем нужно профилю: {1} или новее.'
    'Iso.Copying'               = 'ISO подключён как {0}, копирую файлы...'
    'Iso.RobocopyFailed'        = 'robocopy завершился с кодом {0}'
    'Iso.NoInstallImage'        = 'В папке sources не найден install.wim или install.esd.'
    'Iso.HintProWorkstations'   = 'Pro для мощных рабочих станций: ReFS, больше процессоров и памяти'
    'Iso.HintProEducation'      = 'Pro для учебных заведений'
    'Iso.HintEducation'         = 'для учебных заведений, по возможностям близка к Корпоративной'
    'Iso.HintEnterprise'        = 'корпоративная: всё из Pro плюс функции для организаций, нужна корпоративная лицензия'
    'Iso.HintSingleLanguage'    = 'Домашняя с одним языком интерфейса, сменить язык нельзя'
    'Iso.HintPro'               = 'BitLocker, групповые политики, Hyper-V, удалённый рабочий стол; подходит большинству'
    'Iso.HintHome'              = 'для домашнего ПК, без BitLocker, групповых политик и Hyper-V'
    'Iso.HintN'                 = '{0}. Версия N: без мультимедийных компонентов'
    'Iso.AvailableEditions'     = 'Доступные редакции:'
    'Iso.NoEditionIndex'        = 'В образе нет редакции с номером {0}. Выберите номер из списка выше.'
    'Iso.EditionNotFound'       = 'Редакция ''{0}'' не найдена. Укажите имя из списка выше в кавычках или номер через -Index.'
    'Iso.SingleEdition'         = 'В образе одна редакция: {0}'
    'Iso.ChooseEdition'         = 'Какую редакцию Windows подготовить? В итоговом ISO останется только она.'
    'Iso.ChooseEditionHint'     = 'Если сомневаетесь, выбирайте ту, на которую у вас есть ключ (обычно Home или Pro).'
    'Iso.EditionPrompt'         = 'Введите номер редакции'
    'Iso.NoSuchNumber'          = 'Такого номера нет в списке, попробуйте ещё раз.'
    'Iso.DialogTitle'           = 'Выберите ISO-образ Windows 11'
    'Iso.DialogFilter'          = 'Образ диска (*.iso)|*.iso'
    'Iso.SelectCancelled'       = 'Выбор ISO отменён.'
    'Iso.PathPrompt'            = 'Путь к ISO (можно перетащить файл в это окно)'
    'Iso.FileNotIso'            = 'Файл не найден или это не ISO: {0}'
}
