# Строки Private\Profile.ps1.
@{
    'Profile.NotFound'             = 'Профиль не найден: {0}'
    'Profile.CategoryNoId'         = 'В профиле {0} у одной из категорий не указан Id.'
    'Profile.CategoryIdRepeated'   = 'В профиле {0} Id категории ''{1}'' повторяется.'
    'Profile.DefaultCategoryName'  = 'Профиль'
    'Profile.UnknownHive'          = 'Неизвестный куст ''{0}'' в категории ''{1}''. Допустимо: {2}'
    'Profile.RegistryNoPath'       = 'У записи реестра для куста {0} в категории ''{1}'' не указан Path.'
    'Profile.RegistryEntryProblem' = 'Запись реестра {0}\{1} в категории ''{2}'': {3}'
    'Profile.CountAppx'            = 'приложений: {0}'
    'Profile.CountCapabilities'    = 'компонентов: {0}'
    'Profile.CountFeatures'        = 'функций: {0}'
    'Profile.CountPackages'        = 'пакетов: {0}'
    'Profile.CountRegistry'        = 'реестр: {0}'
    'Profile.CategoryNotFound'     = 'Категории ''{0}'' нет в профиле. Доступные Id: {1}'
    'Profile.CategoriesIntro'      = 'Категории профиля. [x] будет применена, [ ] пропущена.'
    'Profile.CategoriesPrompt'     = 'Номера категорий, чтобы включить или выключить их (через пробел), или Enter, чтобы продолжить'
    'Profile.NoSuchCategoryNumber' = 'Номера {0} нет в списке.'
    'Profile.NoProfiles'           = 'В папке {0} нет профилей (*.json).'
    'Profile.Single'               = 'Профиль: {0}'
    'Profile.ChooseIntro'          = 'Профиль определяет, что будет удалено и изменено в образе:'
    'Profile.Prompt'               = 'Введите номер профиля'
    'Profile.NoSuchNumber'         = 'Такого номера нет в списке, попробуйте ещё раз.'
}
