# Строки Private\Servicing.ps1.
@{
    'Servicing.UpdatesTitle'    = 'Обновления'
    'Servicing.DriversTitle'    = 'Драйверы'
    'Servicing.UpdatesIn'       = 'Обновления в {0}'
    'Servicing.DriversIn'       = 'Драйверы в {0}'
    'Servicing.WhereSetup'      = 'установщике'
    'Servicing.Installing'      = '[{0}/{1}] Устанавливаю {2} ({3})...'
    'Servicing.UpdateFailed'    = 'Не удалось установить {0}: {1}'
    'Servicing.DriverFailed'    = 'Не удалось добавить {0}: {1}'
    'Servicing.Cleanup'         = 'Удаляю старые версии файлов после обновлений...'
    'Servicing.NoWinre'         = 'В образе нет Windows\System32\Recovery\Winre.wim, среда восстановления пропущена.'
    'Servicing.NoBootWim'       = 'В ISO нет sources\boot.wim, установщик обновить нельзя.'
    'Servicing.Recompressing'   = 'Пересжимаю {0}...'
    'Servicing.SizeChange'      = '{0}: было {1}, стало {2}'
    'Servicing.SafeOSIn'        = 'Safe OS Dynamic Update в {0}'
    'Servicing.SetupDUTitle'    = 'Setup Dynamic Update'
    'Servicing.Expanding'       = '[{0}/{1}] Распаковываю {2} ({3}) в sources...'
    'Servicing.ExpandFailed'    = 'Не удалось распаковать {0}: expand.exe вернул код {1}'
    'Servicing.SetupFilesTitle' = 'Файлы установщика'
    'Servicing.SetupFilesDone'  = '{0} скопированы из boot.wim в sources'
    'Servicing.SetupFileFailed' = 'Не удалось скопировать {0} из boot.wim в sources: {1}'
}
